import { JobDetails, JobDetailsSummary } from "./job_listing-types";

export const fakeJobData: JobDetails[] = [
  {
    id: 0,
    company: {
      name: "CodeRex",
      link: "https://www.example.com/company1",
      imgURL: "/images/mockData/job_0.png",
    },
    jobTitle: "Software Engineer",
    location: "New York, NY",
    datePosted: new Date("2023-08-24T10:00:00Z"),
    techStacks: ["JavaScript", "React", "Node.js"],
    jobType: "Full-Time",
    salaryRange: {
      currency: "USD",
      min: 80000,
      max: 100000,
      isEstimate: true,
      similarJobSalary: {
        currency: "USD",
        min: 80000,
        max: 100000,
        isEstimate: true,
      },
    },
    techJobType: "Fullstack",
    seniority: ["Junior", "Mid"],
    yoe: "1-3 years",
    jobDescription: `Activate Interactive Pte Ltd (Activate) is a leading IT solution and service provider headquartered in Singapore with a presence in Malaysia and Indonesia. Our clients are empowered with quality, cost-effective, and impactful end-to-end application development, like mobile and web applications, and cloud technology that remove technology roadblocks and increase their business efficiency.\n\nWe believe in positively impacting the lives of people around us and the environment we live in through the use of technology. Hence, we are committed to providing a conducive environment for all employees to realize their full potential, who in turn have the opportunity to continuously drive innovation.\n\nWe are searching for our next team members to join our growing team.\n\nIf you love the idea of being part of a growing company with exciting prospects in mobile and web technologies that create a positive impact on peoples lives, then we would love to hear from you.\n\nWe are seeking a talented and motivated Mobile Applications Developer to join our growing team. In this role, you will be responsible for designing, building, and maintaining high-quality mobile applications that deliver exceptional user experiences. You will work closely with cross-functional teams, including designers, product managers, and backend engineers, to create seamless and engaging mobile experiences for our users.\n\n\n## What will you do?\n\n- Mobile application development and applied research on Android, iOS, and/or Appcelerator platforms\n- J2EE/ASP.NET software development, involving the use of databases\n- Software support and maintenance of deployed products and solutions.\n\n\n## Requirements\n\n- Knowledge of Object-Oriented Programming and SQL\n- At least 2-3 years of experience with native mobile features such as GPS, accelerometer, push notifications, etc.\n- At least 2-3 years of experience in cross-platform mobile development tools such as React Native Framework (mandatory) and Titanium Appcelerator\n- Experienced in developing on Unix/Linux environments\n- Enjoy constant learning and working with new technologies\n\n\n ## Benefits\n\n- Fun working environment\n- Employee Wellness Program\n- Flexible Benefits\n\nActivate Interactive Singapore is an equal opportunity employer. Employment decisions will be based on merit, qualifications, and abilities. Activate Interactive Pte Ltd does not discriminate in employment opportunities or practices based on race, color, religion, sex, sexuality, national origin, age, disability, marital status, or any other characteristics protected by law.\n\nProtecting your privacy and the security of your data are longstanding top priorities for Activate Interactive Pte Ltd.\n\nYour personal data will be processed for the purposes of managing Activate Interactive Pte Ltds recruitment-related activities, which include setting up and conducting interviews and tests for applicants, evaluating and assessing the results, and as is otherwise needed in the recruitment and hiring processes.\n\nPlease consult our [Privacy Notice](https://www.activate.sg/privacy-policy) to know more about how we collect, use, and transfer the personal data of our candidates. Here you can find how you can request for access, correction, and/or withdrawal of your Personal Data.`,
    rating: 3.2,
    similarJobType: "Software Engineer",
  },
  {
    id: 1,
    company: {
      name: "TechCo",
      link: "https://www.example.com",
      imgURL: "/images/mockData/job_1.png",
    },
    jobTitle: "Senior Software Engineer",
    location: "San Francisco, CA",
    datePosted: new Date("2023-08-28"),
    techStacks: ["React", "Node.js", "TypeScript"],
    jobType: "Full-time",
    techJobType: "Backend",
    salaryRange: {
      currency: "USD",
      min: 100000,
      max: 130000,
      isEstimate: false,
    },
    rating: 4.5,
    seniority: ["Senior"],
    yoe: "5+ years",
    jobDescription: `# Senior Software Engineer\n\nTechCo is seeking a Senior Software Engineer to join our talented team.\n\n\n## Responsibilities\n\n- Develop high-quality software solutions...\n\n- Collaborate with cross-functional teams...\n\n- Participate in code reviews...\n\n\n## Qualifications\n\n- Bachelor's degree in Computer Science...\n\n- Strong experience with React and Node.js...\n\n- Excellent problem-solving skills...
        `,
    similarJobType: "Software Engineer",
  },
  {
    id: 2,
    company: {
      name: "CodeCrafters",
      link: "https://www.codecrafters.com",
      imgURL: `/images/mockData/job_2.png`,
    },
    jobTitle: "Data Scientist",
    location: "Seattle, WA",
    datePosted: new Date("2023-08-26"),
    techStacks: ["Python", "Machine Learning", "SQL"],
    techJobType: "Data Science",
    salaryRange: {
      currency: "USD",
      min: 90000,
      max: 120000,
      isEstimate: false,
    },
    rating: 4.2,
    seniority: ["Mid", "Senior"],
    yoe: "3-7 years",
    jobDescription:
      "# Data Scientist\n\nJoin our team at CodeCrafters as a Data Scientist and contribute to...\n\nResponsibilities:\n\n- Analyze large datasets to extract meaningful insights...\n- Build and deploy machine learning models...\n- Collaborate with cross-functional teams...\n\nQualifications:\n\n- Master's or Ph.D. in a quantitative field...\n- Proficient in Python, machine learning techniques...\n- Strong problem-solving and analytical skills...",
    similarJobType: "Machine Learning Engineer",
  },
  {
    id: 3,
    company: {
      name: "EcoTech Solutions",
      link: "https://www.ecotech-solutions.com",
      imgURL: `/images/mockData/job_3.png`,
    },
    jobTitle: "Machine Learning Engineer",
    location: "Portland, OR",
    datePosted: new Date("2023-08-25"),
    techStacks: ["Data Science", "R", "Data Analysis"],
    techJobType: "Research",
    salaryRange: {
      currency: "USD",
      min: 75000,
      max: 95000,
      isEstimate: false,
      similarJobSalary: {
        currency: "USD",
        min: 70000,
        max: 100000,
        isEstimate: true,
      },
    },
    rating: 4.8,
    seniority: ["Entry", "Mid"],
    yoe: "1-4 years",
    jobDescription:
      "EcoTech Solutions is seeking a Machine Learning Engineer to contribute...\n\nResponsibilities:\n\n- Conduct fieldwork and collect environmental data...\n- Analyze and interpret data using GIS and statistical tools...\n- Prepare technical reports and presentations...\n\nQualifications:\n\n- Bachelor's or Master's degree in Environmental Science...\n- Proficient in GIS software, data analysis techniques...\n- Strong written and verbal communication skills...",
    similarJobType: "GIS Analyst",
  },
  {
    id: 4,
    company: {
      name: "TechInnovators",
      link: "https://www.techinnovators.com",
      imgURL: `/images/mockData/job_4.png`,
    },
    jobTitle: "Cybersecurity Analyst",
    location: "Chicago, IL",
    datePosted: new Date("2023-08-25"),
    techStacks: ["Security", "Networks", "SIEM"],
    techJobType: "Security",
    salaryRange: {
      currency: "USD",
      min: 85000,
      max: 110000,
      isEstimate: false,
    },
    rating: 4.4,
    seniority: ["Mid"],
    yoe: "3-6 years",
    jobDescription:
      "# Cybersecurity Analyst\n\nTechInnovators is seeking a Cybersecurity Analyst to ensure the security of our systems...\n\nResponsibilities:\n\n- Monitor and analyze security alerts and incidents...\n- Implement security measures and best practices...\n- Collaborate with IT teams to address vulnerabilities...\n\nQualifications:\n\n- Bachelor's degree in Computer Science or related field...\n- Proficient in cybersecurity techniques, network security, and SIEM tools...\n- Strong understanding of threat detection and response...",
    similarJobType: "Security Engineer",
  },
  {
    id: 5,
    company: {
      name: "DataTech Solutions",
      link: "https://www.datatech-solutions.com",
      imgURL: `/images/mockData/job_5.png`,
    },
    jobTitle: "Database Administrator",
    location: "Houston, TX",
    datePosted: new Date("2023-08-24"),
    techStacks: ["Database", "SQL"],
    techJobType: "Database",
    salaryRange: {
      currency: "USD",
      min: 80000,
      max: 105000,
      isEstimate: true,
    },
    rating: 4.0,
    seniority: ["Mid"],
    yoe: "3-6 years",
    jobDescription:
      "# Database Administrator\n\nDataTech Solutions is looking for a Database Administrator to manage our data infrastructure...\n\nResponsibilities:\n\n- Design, implement, and maintain databases...\n- Optimize database performance and troubleshoot issues...\n- Collaborate with development teams for data integration...\n\nQualifications:\n\n- Bachelor's degree in Computer Science or related field...\n- Proficient in database management, SQL, and performance tuning...\n- Strong problem-solving and communication skills...",
    similarJobType: "Data Engineer",
  },
  {
    id: 6,
    company: {
      name: "TechSolutions",
      link: "https://www.techsolutions.com",
      imgURL: `/images/mockData/job_6.png`,
    },
    jobTitle: "Frontend Developer",
    location: "Los Angeles, CA",
    datePosted: new Date("2023-08-23"),
    techStacks: ["React", "JavaScript", "HTML", "CSS"],
    techJobType: "Frontend",
    salaryRange: {
      currency: "USD",
      min: 85000,
      max: 110000,
      isEstimate: false,
      similarJobSalary: {
        currency: "USD",
        min: 70000,
        max: 100000,
        isEstimate: true,
      },
    },
    rating: 4.3,
    seniority: ["Mid"],
    yoe: "2-5 years",
    jobDescription:
      "# Frontend Developer\n\nTechSolutions is looking for a Frontend Developer to build user interfaces...\n\nResponsibilities:\n\n- Develop interactive and responsive web applications...\n- Collaborate with designers to implement UI/UX designs...\n- Write clean and modular code using React and JavaScript...\n\nQualifications:\n\n- Bachelor's degree in Computer Science or related field...\n- Proficient in React, JavaScript, HTML, and CSS...\n- Strong problem-solving and UI development skills...",
    similarJobType: "UI Developer",
  },
  {
    id: 7,
    company: {
      name: "CodeMasters",
      link: "https://www.codemasters.com",
      imgURL: `/images/mockData/job_7.png`,
    },
    jobTitle: "Software QA Engineer",
    location: "Austin, TX",
    datePosted: new Date("2023-08-22"),
    techStacks: ["QA", "Testing", "Selenium"],
    techJobType: "Quality Assurance",
    salaryRange: {
      currency: "USD",
      min: 75000,
      max: 100000,
      isEstimate: false,
      similarJobSalary: {
        currency: "USD",
        min: 70000,
        max: 100000,
        isEstimate: true,
      },
    },
    rating: 4.1,
    seniority: ["Mid"],
    yoe: "2-5 years",
    jobDescription:
      "# Software QA Engineer\n\nCodeMasters is seeking a Software QA Engineer to ensure the quality of our products...\n\nResponsibilities:\n\n- Develop and execute automated test scripts...\n- Identify and report software defects and issues...\n- Collaborate with development teams to improve product quality...\n\nQualifications:\n\n- Bachelor's degree in Computer Science or related field...\n- Proficient in quality assurance methodologies, automated testing, and Selenium...\n- Strong problem-solving and attention to detail...",
    similarJobType: "Test Automation Engineer",
  },
  {
    id: 8,
    company: {
      name: "TechInnovators",
      link: "https://www.techinnovators.com",
      imgURL: `/images/mockData/job_8.png`,
    },
    jobTitle: "Full Stack Developer",
    location: "Denver, CO",
    datePosted: new Date("2023-08-21"),
    techStacks: ["Node.js", "Express", "React", "MongoDB"],
    techJobType: "Full Stack",
    salaryRange: {
      currency: "USD",
      min: 95000,
      max: 125000,
      isEstimate: false,
      similarJobSalary: {
        currency: "USD",
        min: 70000,
        max: 100000,
        isEstimate: true,
      },
    },
    rating: 4.5,
    seniority: ["Mid"],
    yoe: "3-6 years",
    jobDescription:
      "# Full Stack Developer\n\nTechInnovators is looking for a Full Stack Developer to work on end-to-end solutions...\n\nResponsibilities:\n\n- Develop and maintain both frontend and backend components...\n- Collaborate with teams to design and implement features...\n- Manage databases and server-side logic using Node.js and Express...\n\nQualifications:\n\n- Bachelor's degree in Computer Science or related field...\n- Proficient in Node.js, Express, React, and MongoDB...\n- Strong problem-solving and full stack development skills...",
    similarJobType: "Web Developer",
  },
  {
    id: 9,
    company: {
      name: "TechVision",
      link: "https://www.techvision.com",
      imgURL: `/images/mockData/job_9.png`,
    },
    jobTitle: "DevOps Engineer",
    location: "Seattle, WA",
    datePosted: new Date("2023-08-20"),
    techStacks: ["Docker", "Kubernetes", "AWS", "CI/CD"],
    techJobType: "DevOps",
    salaryRange: {
      currency: "USD",
      min: 100000,
      max: 140000,
      isEstimate: true,
    },
    rating: 4.7,
    seniority: ["Mid", "Senior"],
    yoe: "4-8 years",
    jobDescription:
      "# DevOps Engineer\n\nTechVision is seeking a DevOps Engineer to streamline our software development and deployment processes...\n\nResponsibilities:\n\n- Design and implement automated deployment pipelines...\n- Manage Docker and Kubernetes clusters for containerization...\n- Collaborate with development teams to ensure smooth integration...\n\nQualifications:\n\n- Bachelor's degree in Computer Science or related field...\n- Proficient in Docker, Kubernetes, AWS, and CI/CD practices...\n- Strong problem-solving and automation skills...",
    similarJobType: "Site Reliability Engineer",
  },
];
